server:
  port: 8081
spring:
    application:
       name: fly-user-service
eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      description: user service：base api，account api
logging:
  level:
    org:
      springframework:
        security: DEBUG
